# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 09:06
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title')),
                ('content', models.TextField(null=True, verbose_name='Content')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('search_index', djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False)),
            ],
            options={
                'verbose_name': 'book',
                'ordering': ['title'],
                'verbose_name_plural': 'books',
            },
        ),
    ]
