# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20170109_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
    ]
